export const t = {
  title: "WoW Addons",
  loading: "Loading…",
  refresh: "Refresh",
  // central full-screen view
  openMain: "Open WoW Addons",
  openMainDesc: "Installed addons, search, WoW versions, undo and WowUp-CF.",
  pages: { installed: "Installed", get: "Get addons", versions: "WoW versions", undo: "Undo", wowup: "WowUp-CF",
    notes: "Notes" },
  setupInView: "Set it up in WoW Addons.",
  // WowUp-CF
  wowup: "WowUp-CF",
  wowupMissing: "WowUp-CF is not installed",
  wowupMissingDesc: "The plugin uses WowUp-CF (CurseForge build) as its engine and runs it without a window.",
  installWowup: "Install WowUp-CF",
  installWowupDesc: "Downloads the latest release from GitHub and checks it against the published checksums.",
  useFound: "Use this WowUp-CF",
  verified: "verified",
  unverified: "not verified",
  channel: "channel",
  wowupRunning: "WowUp-CF is open. Close it to update from here.",
  updateWowup: "Update WowUp-CF",
  updateWowupDesc: "Tested on a copy of your profile before switching.",
  // addons
  addons: "Addons",
  version: "Version",
  noInstallations: "WowUp-CF has no WoW installation yet.",
  addonsSummary: (n: number, u: number, i: number) => `${n} addons · ${u} updates · ${i} incompatible`,
  updateAll: "Update all",
  updateAllVersionsDesc: "Checks and installs updates for every WoW version.",
  check: "Check for updates",
  update: "Update",
  lastRun: "Last run",
  updatedN: (n: number) => (n === 1 ? "1 addon updated" : `${n} addons updated`),
  nothingUpdated: "no updates installed",
  failed: "failed",
  timedOut: "timed out",
  compat: { ok: "", outdated: "out of date", incompatible: "does not load", unknown: "" } as Record<string, string>,
  missingFolders: "folders missing",
  ignored: "ignored",
  unmanaged: "Not managed by WowUp",
  unmanagedDesc: "Folders in AddOns that WowUp-CF does not manage (copied by hand or installed by another tool).",
  noAddons: "No addons installed for this WoW version yet.",
  neededBy: (names: string[]) => `needed by ${names.join(", ")}`,
  removeTitle: (name: string) => `Remove ${name}?`,
  removeBody: (folders: string[], requiredBy: string[]) =>
    `Deletes ${!folders.length ? "its entry" : folders.length > 3 ? `${folders.slice(0, 2).join(", ")} and ${folders.length - 2} more folders`
      : folders.join(", ")} from the AddOns folder and removes it from WowUp-CF.` +
    `${requiredBy.length ? ` ${requiredBy.join(", ")} need${requiredBy.length === 1 ? "s" : ""} it and may stop working.` : ""}` +
    " The folders are kept in a snapshot, see Undo.",
  removeWithDeps: (names: string[]) => `Also remove ${names.join(", ")}`,
  removeFolderTitle: (folder: string) => `Remove the folder ${folder}?`,
  removeFolderBody: "Deletes this folder from AddOns. WowUp-CF does not manage it. It is kept in a snapshot, see Undo.",
  removedN: (names: string) => `Removed: ${names}`,
  noGame: "No WoW installation in this folder",
  noGameDesc: "Only an AddOns folder is left here (e.g. from a deleted Proton prefix), so the game does not use these addons. Updates skip this version.",
  moveTo: "Move to the installed game",
  moveTitle: "Move this WoW version?",
  moveBody: (from: string, to: string, replaces: string | null) =>
    `WowUp-CF will use ${to} instead of ${from}. Addon folders are copied, addons without folders are reinstalled on the next update. The old folder is left as it is.${replaces ? ` The empty entry "${replaces}" for the same folder is removed.` : ""}`,
  move: "Move",
  // versions
  manageVersions: "Manage WoW versions",
  addAllFound: (n: number) => `Add all found (${n})`,
  inWowup: "In WowUp-CF",
  foundNotInWowup: "Found, not in WowUp-CF",
  nothingFound: "Nothing else found.",
  add: "Add",
  unsupportedVersion: "Not supported by this WowUp-CF version",
  addFolder: "Add a WoW folder…",
  addFolderDesc: "Pick a Wine prefix, a \"World of Warcraft\" folder or a version folder such as _retail_.",
  searchFolders: "Search folders",
  searchFoldersDesc: "Searched up to three levels deep, in addition to Steam, Bottles, Lutris, Heroic, Wine and CrossOver.",
  addSearchFolder: "Add search folder…",
  remove: "Remove",
  addedByHand: "Added by hand",
  forget: "Forget",
  scanRemovable: "Search SD cards and USB drives",
  drives: "Drives",
  searchAgain: "Search again",
  sourcesChecked: "Found in",
  sourceNames: { steam: "Steam", bottles: "Bottles", lutris: "Lutris", heroic: "Heroic", wine: "Wine",
    crossover: "CrossOver", search: "Search folders", removable: "Drives", manual: "Added by hand" } as Record<string, string>,
  unmanagedHint: "Addons already present in a newly added version show as \"not managed\" until WowUp-CF scans them (open WowUp-CF once) or you install them via Get addons.",
  addedN: (n: number) => (n === 1 ? "1 WoW version added" : `${n} WoW versions added`),
  // undo
  undoIntro: "Before every update run and every removal the AddOns folder is saved as a snapshot (hard links, it takes almost no space). The newest snapshots are listed here.",
  noSnapshots: "No snapshots yet.",
  snapRemoved: (names: string[]) => `Removed ${names.join(", ")}`,
  snapBeforeUpdate: "Before an update run",
  snapBeforeRestore: "Before restoring a snapshot",
  restoreRemovalTitle: "Put the removed addons back?",
  restoreRemovalBody: "Puts the removed folders back and adds the addons to WowUp-CF again. Addons installed again since then stay as they are.",
  undoTitle: "Restore addon folders?",
  undoBody: "The current folders are kept as a new snapshot first. WowUp will offer the update again; ignore the addon in WowUp to stay on the old version.",
  restore: "Restore",
  // get addons (full screen)
  getAddonsIntro: "Addons are installed and kept up to date by WowUp-CF. Target version:",
  searchLabel: "Search WoWInterface and WowUp Hub",
  search: "Search",
  searching: "Searching…",
  resultsWowi: "WoWInterface",
  resultsHub: "WowUp Hub",
  popularWowi: "Popular on WoWInterface",
  featuredHub: "Featured on WowUp Hub",
  noResults: "No results.",
  install: "Install",
  sortBy: "Sort by",
  sorts: { relevance: "Best match", popular: "Popular", downloads: "Most downloads", favorites: "Most favorites",
    updated: "Recently updated", name: "Name" } as Record<string, string>,
  sortHint: "Popular: downloads this month on WoWInterface, featured on WowUp Hub. WowUp Hub has no favorites and sorts by downloads instead. CurseForge ratings are not available without an API key.",
  favorites: "favorites",
  updatedOn: "updated",
  installedBadge: "Installed",
  presentNote: "Folders already in AddOns (not managed by WowUp) – installing replaces them.",
  maybeIncompatible: "Not listed for this WoW version",
  downloads: "downloads",
  forVersions: "for",
  curseforge: "CurseForge",
  curseforgeIntro: "CurseForge offers no search without an API key. Install an addon by its project ID (shown on the addon's CurseForge page under \"About Project\"), or search in WowUp-CF's own window.",
  cfProjectId: "CurseForge project ID",
  openWowup: "Search CurseForge in WowUp-CF",
  openWowupHint: "Opens WowUp-CF's window as a Steam shortcut. Close it via the Steam button → Exit game (or below) to update from here again.",
  closeWowup: "Close WowUp-CF",
  openWowupApp: "Open WowUp-CF window",
  openWowupAppDesc: "Opens WowUp-CF's own window as a Steam shortcut, e.g. for its settings. Close it via the Steam button → Exit game to update from here again.",
  checkWowup: "Check for WowUp-CF update",
  wowupUpToDate: "WowUp-CF is up to date",
  wowupPath: "AppImage",
  installedN: (names: string) => `Installed: ${names}`,
  failedN: (n: number) => (n === 1 ? "1 addon could not be installed" : `${n} addons could not be installed`),
  installedLabel: "installed",
  // jobs
  working: "Working…",
  jobDone: {
    run: "Addon run finished",
    import: "WoW versions added",
    restore: "Addon folders restored",
    wowup_install: "WowUp-CF installed",
    wowup_update: "WowUp-CF updated",
    install: "Installation finished",
    remove: "Addons removed",
    versions: "WoW versions",
    selftest: "Self-test finished",
  } as Record<string, string>,
  jobFailed: "failed",
  busy: "Another task is still running.",
  // maintenance
  maintenance: "Maintenance",
  pluginVersion: "Plugin version",
  checkPluginUpdate: "Check for plugin update",
  installUpdate: "Install plugin update",
  updateAvailable: "Update available",
  upToDate: "Up to date",
  updateFailed: "Update check failed",
  autoRestart: "Restart Steam after plugin updates",
  autoRestartDesc: "Loads the new interface right away.",
  staleUi: "Interface is older than the backend",
  restartSteam: "Restart Steam",
  restartingSteam: "Restarting Steam to load the updated plugin…",
  diagnostics: "Diagnostics",
  showDiagnostics: "Show diagnostics",
  diagnosticsDesc: "A summary for bug reports: versions, paths, WoW versions and the last run.",
  noNotes: "Nothing to report.",
  pluginUpdatesInQam: "Plugin updates are in the Quick Access menu.",
  warnings: "Notes",
};
