export const t = {
  title: "WoW Addons",
  loading: "Loading…",
  refresh: "Refresh",
  // WowUp-CF
  wowup: "WowUp-CF",
  wowupMissing: "WowUp-CF is not installed",
  wowupMissingDesc: "The plugin uses WowUp-CF (CurseForge build) as its engine and runs it without a window.",
  installWowup: "Install WowUp-CF",
  installWowupDesc: "Downloads the latest release from GitHub and checks it against the published checksums.",
  useFound: "Use this WowUp-CF",
  verified: "verified",
  unverified: "not verified",
  channel: "channel",
  wowupRunning: "WowUp-CF is open. Close it to update from here.",
  updateWowup: "Update WowUp-CF",
  updateWowupDesc: "Tested on a copy of your profile before switching.",
  // addons
  addons: "Addons",
  version: "Version",
  noInstallations: "WowUp-CF has no WoW installation yet.",
  addonsSummary: (n: number, u: number, i: number) => `${n} addons · ${u} updates · ${i} incompatible`,
  updateAll: "Update all",
  updateAllDesc: "Checks and installs updates for this WoW version.",
  check: "Check for updates",
  checkDesc: "Only looks for new versions, installs nothing.",
  update: "Update",
  lastRun: "Last run",
  updatedN: (n: number) => (n === 1 ? "1 addon updated" : `${n} addons updated`),
  nothingUpdated: "no updates installed",
  failed: "failed",
  timedOut: "timed out",
  compat: { ok: "", outdated: "out of date", incompatible: "does not load", unknown: "" } as Record<string, string>,
  missingFolders: "folders missing",
  ignored: "ignored",
  unmanaged: "Not managed by WowUp",
  // versions
  versions: "WoW versions",
  notInWowup: "Found in the Battle.net prefix, not in WowUp yet",
  importVersions: "Add to WowUp",
  importVersionsDesc: "Lets WowUp import every version Battle.net has installed.",
  // safety
  safety: "Safety",
  undo: "Undo last update",
  undoDesc: (when: string) => `Restores the addon folders from ${when}.`,
  undoTitle: "Restore addon folders?",
  undoBody: "The current folders are kept as a new snapshot first. WowUp will offer the update again; ignore the addon in WowUp to stay on the old version.",
  restore: "Restore",
  // jobs
  working: "Working…",
  jobDone: {
    run: "Addon run finished",
    import: "WoW versions added",
    restore: "Addon folders restored",
    wowup_install: "WowUp-CF installed",
    wowup_update: "WowUp-CF updated",
    selftest: "Self-test finished",
  } as Record<string, string>,
  jobFailed: "failed",
  busy: "Another task is still running.",
  // maintenance
  maintenance: "Maintenance",
  pluginVersion: "Plugin version",
  checkPluginUpdate: "Check for plugin update",
  installUpdate: "Install plugin update",
  updateAvailable: "Update available",
  upToDate: "Up to date",
  updateFailed: "Update check failed",
  autoRestart: "Restart Steam after plugin updates",
  autoRestartDesc: "Loads the new interface right away.",
  staleUi: "Interface is older than the backend",
  restartSteam: "Restart Steam",
  restartingSteam: "Restarting Steam to load the updated plugin…",
  diagnostics: "Diagnostics",
  warnings: "Notes",
};
