export const t = {
  title: "WoW Addons",
  loading: "Loading…",
  refresh: "Refresh",
  // WowUp-CF
  wowup: "WowUp-CF",
  wowupMissing: "WowUp-CF is not installed",
  wowupMissingDesc: "The plugin uses WowUp-CF (CurseForge build) as its engine and runs it without a window.",
  installWowup: "Install WowUp-CF",
  installWowupDesc: "Downloads the latest release from GitHub and checks it against the published checksums.",
  useFound: "Use this WowUp-CF",
  verified: "verified",
  unverified: "not verified",
  channel: "channel",
  wowupRunning: "WowUp-CF is open. Close it to update from here.",
  updateWowup: "Update WowUp-CF",
  updateWowupDesc: "Tested on a copy of your profile before switching.",
  // addons
  addons: "Addons",
  version: "Version",
  noInstallations: "WowUp-CF has no WoW installation yet.",
  addonsSummary: (n: number, u: number, i: number) => `${n} addons · ${u} updates · ${i} incompatible`,
  updateAll: "Update all",
  updateAllDesc: "Checks and installs updates for this WoW version.",
  check: "Check for updates",
  checkDesc: "Only looks for new versions, installs nothing.",
  update: "Update",
  lastRun: "Last run",
  updatedN: (n: number) => (n === 1 ? "1 addon updated" : `${n} addons updated`),
  nothingUpdated: "no updates installed",
  failed: "failed",
  timedOut: "timed out",
  compat: { ok: "", outdated: "out of date", incompatible: "does not load", unknown: "" } as Record<string, string>,
  missingFolders: "folders missing",
  ignored: "ignored",
  unmanaged: "Not managed by WowUp",
  noGame: "No WoW installation in this folder",
  noGameDesc: "Only an AddOns folder is left here (e.g. from a deleted Proton prefix), so the game does not use these addons. Updates skip this version.",
  moveTo: "Move to the installed game",
  moveToDesc: (dir: string) => `Keeps the addon list and copies the addon folders to ${dir}.`,
  moveTitle: "Move this WoW version?",
  moveBody: (from: string, to: string, replaces: string | null) =>
    `WowUp-CF will use ${to} instead of ${from}. Addon folders are copied, addons without folders are reinstalled on the next update. The old folder is left as it is.${replaces ? ` The empty entry "${replaces}" for the same folder is removed.` : ""}`,
  move: "Move",
  // versions
  versions: "WoW versions",
  manageVersions: "Manage WoW versions",
  manageVersionsDesc: "Found installations, folders to search, add a folder by hand.",
  versionsSummary: (inWowup: number, found: number) =>
    `${inWowup} in WowUp${found ? ` · ${found} found, not in WowUp` : ""}`,
  addAllFound: (n: number) => `Add all found (${n})`,
  inWowup: "In WowUp-CF",
  foundNotInWowup: "Found, not in WowUp-CF",
  nothingFound: "Nothing else found.",
  add: "Add",
  addAll: "Add all",
  unsupportedVersion: "Not supported by this WowUp-CF version",
  addFolder: "Add a WoW folder…",
  addFolderDesc: "Pick a Wine prefix, a \"World of Warcraft\" folder or a version folder such as _retail_.",
  searchFolders: "Search folders",
  searchFoldersDesc: "Searched up to three levels deep, in addition to Steam, Bottles, Lutris, Heroic, Wine and CrossOver.",
  addSearchFolder: "Add search folder…",
  remove: "Remove",
  addedByHand: "Added by hand",
  forget: "Forget",
  scanRemovable: "Search SD cards and USB drives",
  drives: "Drives",
  searchAgain: "Search again",
  sourcesChecked: "Found in",
  sourceNames: { steam: "Steam", bottles: "Bottles", lutris: "Lutris", heroic: "Heroic", wine: "Wine",
    crossover: "CrossOver", search: "Search folders", removable: "Drives", manual: "Added by hand" } as Record<string, string>,
  unmanagedHint: "Addons already present in a newly added version show as \"not managed\" until WowUp-CF scans them (open WowUp-CF once) or you install them via Get addons.",
  addedN: (n: number) => (n === 1 ? "1 WoW version added" : `${n} WoW versions added`),
  // safety
  safety: "Safety",
  undo: "Undo last update",
  undoDesc: (when: string) => `Restores the addon folders from ${when}.`,
  undoTitle: "Restore addon folders?",
  undoBody: "The current folders are kept as a new snapshot first. WowUp will offer the update again; ignore the addon in WowUp to stay on the old version.",
  restore: "Restore",
  // get addons (full screen)
  getAddons: "Get addons",
  getAddonsDesc: "Search WoWInterface and WowUp Hub, or install from CurseForge.",
  getAddonsIntro: "Addons are installed and kept up to date by WowUp-CF. Target version:",
  searchLabel: "Search WoWInterface and WowUp Hub",
  search: "Search",
  searching: "Searching…",
  resultsWowi: "WoWInterface",
  resultsHub: "WowUp Hub",
  popularWowi: "Popular on WoWInterface",
  featuredHub: "Featured on WowUp Hub",
  noResults: "No results.",
  install: "Install",
  installedBadge: "Installed",
  presentNote: "Folders already in AddOns (not managed by WowUp) – installing replaces them.",
  maybeIncompatible: "Not listed for this WoW version",
  downloads: "downloads",
  forVersions: "for",
  curseforge: "CurseForge",
  curseforgeIntro: "CurseForge offers no search without an API key. Install an addon by its project ID (shown on the addon's CurseForge page under \"About Project\"), or search in WowUp-CF's own window.",
  cfProjectId: "CurseForge project ID",
  openWowup: "Search CurseForge in WowUp-CF",
  openWowupHint: "Opens WowUp-CF's window as a Steam shortcut. Close it via the Steam button → Exit game (or below) to update from here again.",
  closeWowup: "Close WowUp-CF",
  back: "Back",
  installedN: (names: string) => `Installed: ${names}`,
  failedN: (n: number) => (n === 1 ? "1 addon could not be installed" : `${n} addons could not be installed`),
  installedLabel: "installed",
  // jobs
  working: "Working…",
  jobDone: {
    run: "Addon run finished",
    import: "WoW versions added",
    restore: "Addon folders restored",
    wowup_install: "WowUp-CF installed",
    wowup_update: "WowUp-CF updated",
    install: "Installation finished",
    versions: "WoW versions",
    selftest: "Self-test finished",
  } as Record<string, string>,
  jobFailed: "failed",
  busy: "Another task is still running.",
  // maintenance
  maintenance: "Maintenance",
  pluginVersion: "Plugin version",
  checkPluginUpdate: "Check for plugin update",
  installUpdate: "Install plugin update",
  updateAvailable: "Update available",
  upToDate: "Up to date",
  updateFailed: "Update check failed",
  autoRestart: "Restart Steam after plugin updates",
  autoRestartDesc: "Loads the new interface right away.",
  staleUi: "Interface is older than the backend",
  restartSteam: "Restart Steam",
  restartingSteam: "Restarting Steam to load the updated plugin…",
  diagnostics: "Diagnostics",
  warnings: "Notes",
};
